/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing BookkeepingIntegrationsGet404Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BookkeepingIntegrationsGet404ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BookkeepingIntegrationsGet404Response
        //private BookkeepingIntegrationsGet404Response instance;

        public BookkeepingIntegrationsGet404ResponseTests()
        {
            // TODO uncomment below to create an instance of BookkeepingIntegrationsGet404Response
            //instance = new BookkeepingIntegrationsGet404Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BookkeepingIntegrationsGet404Response
        /// </summary>
        [Fact]
        public void BookkeepingIntegrationsGet404ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BookkeepingIntegrationsGet404Response
            //Assert.IsType<BookkeepingIntegrationsGet404Response>(instance);
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
