/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing CustomsGood
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomsGoodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomsGood
        //private CustomsGood instance;

        public CustomsGoodTests()
        {
            // TODO uncomment below to create an instance of CustomsGood
            //instance = new CustomsGood();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomsGood
        /// </summary>
        [Fact]
        public void CustomsGoodInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomsGood
            //Assert.IsType<CustomsGood>(instance);
        }


        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'CommodityCode'
        /// </summary>
        [Fact]
        public void CommodityCodeTest()
        {
            // TODO unit test for the property 'CommodityCode'
        }
        /// <summary>
        /// Test the property 'UnitValue'
        /// </summary>
        [Fact]
        public void UnitValueTest()
        {
            // TODO unit test for the property 'UnitValue'
        }
        /// <summary>
        /// Test the property 'UnitWeight'
        /// </summary>
        [Fact]
        public void UnitWeightTest()
        {
            // TODO unit test for the property 'UnitWeight'
        }

    }

}
