/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing Label
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Label
        //private Label instance;

        public LabelTests()
        {
            // TODO uncomment below to create an instance of Label
            //instance = new Label();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Label
        /// </summary>
        [Fact]
        public void LabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" Label
            //Assert.IsType<Label>(instance);
        }


        /// <summary>
        /// Test the property 'Base64'
        /// </summary>
        [Fact]
        public void Base64Test()
        {
            // TODO unit test for the property 'Base64'
        }
        /// <summary>
        /// Test the property 'FileFormat'
        /// </summary>
        [Fact]
        public void FileFormatTest()
        {
            // TODO unit test for the property 'FileFormat'
        }

    }

}
