/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing PickupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PickupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PickupRequest
        //private PickupRequest instance;

        public PickupRequestTests()
        {
            // TODO uncomment below to create an instance of PickupRequest
            //instance = new PickupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PickupRequest
        /// </summary>
        [Fact]
        public void PickupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PickupRequest
            //Assert.IsType<PickupRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CarrierCode'
        /// </summary>
        [Fact]
        public void CarrierCodeTest()
        {
            // TODO unit test for the property 'CarrierCode'
        }
        /// <summary>
        /// Test the property 'PickupAddress'
        /// </summary>
        [Fact]
        public void PickupAddressTest()
        {
            // TODO unit test for the property 'PickupAddress'
        }
        /// <summary>
        /// Test the property 'ConfirmationNumber'
        /// </summary>
        [Fact]
        public void ConfirmationNumberTest()
        {
            // TODO unit test for the property 'ConfirmationNumber'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'ReadyBy'
        /// </summary>
        [Fact]
        public void ReadyByTest()
        {
            // TODO unit test for the property 'ReadyBy'
        }
        /// <summary>
        /// Test the property 'ClosedBy'
        /// </summary>
        [Fact]
        public void ClosedByTest()
        {
            // TODO unit test for the property 'ClosedBy'
        }
        /// <summary>
        /// Test the property 'PackageLocation'
        /// </summary>
        [Fact]
        public void PackageLocationTest()
        {
            // TODO unit test for the property 'PackageLocation'
        }
        /// <summary>
        /// Test the property 'NumberOfPieces'
        /// </summary>
        [Fact]
        public void NumberOfPiecesTest()
        {
            // TODO unit test for the property 'NumberOfPieces'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'IsResidential'
        /// </summary>
        [Fact]
        public void IsResidentialTest()
        {
            // TODO unit test for the property 'IsResidential'
        }
        /// <summary>
        /// Test the property 'Shipments'
        /// </summary>
        [Fact]
        public void ShipmentsTest()
        {
            // TODO unit test for the property 'Shipments'
        }

    }

}
