/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing Printer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrinterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Printer
        //private Printer instance;

        public PrinterTests()
        {
            // TODO uncomment below to create an instance of Printer
            //instance = new Printer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Printer
        /// </summary>
        [Fact]
        public void PrinterInstanceTest()
        {
            // TODO uncomment below to test "IsType" Printer
            //Assert.IsType<Printer>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Hostname'
        /// </summary>
        [Fact]
        public void HostnameTest()
        {
            // TODO unit test for the property 'Hostname'
        }
        /// <summary>
        /// Test the property '_Printer'
        /// </summary>
        [Fact]
        public void _PrinterTest()
        {
            // TODO unit test for the property '_Printer'
        }
        /// <summary>
        /// Test the property 'LabelFormat'
        /// </summary>
        [Fact]
        public void LabelFormatTest()
        {
            // TODO unit test for the property 'LabelFormat'
        }
        /// <summary>
        /// Test the property 'DefaultPrinter'
        /// </summary>
        [Fact]
        public void DefaultPrinterTest()
        {
            // TODO unit test for the property 'DefaultPrinter'
        }
        /// <summary>
        /// Test the property 'DefaultDocumentPrinter'
        /// </summary>
        [Fact]
        public void DefaultDocumentPrinterTest()
        {
            // TODO unit test for the property 'DefaultDocumentPrinter'
        }
        /// <summary>
        /// Test the property 'DefaultPickDocumentPrinter'
        /// </summary>
        [Fact]
        public void DefaultPickDocumentPrinterTest()
        {
            // TODO unit test for the property 'DefaultPickDocumentPrinter'
        }
        /// <summary>
        /// Test the property 'AutoPrint'
        /// </summary>
        [Fact]
        public void AutoPrintTest()
        {
            // TODO unit test for the property 'AutoPrint'
        }
        /// <summary>
        /// Test the property 'StaffAccountId'
        /// </summary>
        [Fact]
        public void StaffAccountIdTest()
        {
            // TODO unit test for the property 'StaffAccountId'
        }

    }

}
