/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessSalesOrderBarcode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessSalesOrderBarcodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessSalesOrderBarcode
        //private ProcessSalesOrderBarcode instance;

        public ProcessSalesOrderBarcodeTests()
        {
            // TODO uncomment below to create an instance of ProcessSalesOrderBarcode
            //instance = new ProcessSalesOrderBarcode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessSalesOrderBarcode
        /// </summary>
        [Fact]
        public void ProcessSalesOrderBarcodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessSalesOrderBarcode
            //Assert.IsType<ProcessSalesOrderBarcode>(instance);
        }


        /// <summary>
        /// Test the property 'Barcode'
        /// </summary>
        [Fact]
        public void BarcodeTest()
        {
            // TODO unit test for the property 'Barcode'
        }

    }

}
