/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentTemplateReceiver
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentTemplateReceiverTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipmentTemplateReceiver
        //private ShipmentTemplateReceiver instance;

        public ShipmentTemplateReceiverTests()
        {
            // TODO uncomment below to create an instance of ShipmentTemplateReceiver
            //instance = new ShipmentTemplateReceiver();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentTemplateReceiver
        /// </summary>
        [Fact]
        public void ShipmentTemplateReceiverInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipmentTemplateReceiver
            //Assert.IsType<ShipmentTemplateReceiver>(instance);
        }


        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }

    }

}
