/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing WaybillShipment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WaybillShipmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WaybillShipment
        //private WaybillShipment instance;

        public WaybillShipmentTests()
        {
            // TODO uncomment below to create an instance of WaybillShipment
            //instance = new WaybillShipment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WaybillShipment
        /// </summary>
        [Fact]
        public void WaybillShipmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" WaybillShipment
            //Assert.IsType<WaybillShipment>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LabelBase64'
        /// </summary>
        [Fact]
        public void LabelBase64Test()
        {
            // TODO unit test for the property 'LabelBase64'
        }

    }

}
