/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShipmondoApi.Dotnet.Model;
using ShipmondoApi.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShipmondoApi.Dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing Webhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Webhook
        //private Webhook instance;

        public WebhookTests()
        {
            // TODO uncomment below to create an instance of Webhook
            //instance = new Webhook();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Webhook
        /// </summary>
        [Fact]
        public void WebhookInstanceTest()
        {
            // TODO uncomment below to test "IsType" Webhook
            //Assert.IsType<Webhook>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Endpoint'
        /// </summary>
        [Fact]
        public void EndpointTest()
        {
            // TODO unit test for the property 'Endpoint'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'ResourceName'
        /// </summary>
        [Fact]
        public void ResourceNameTest()
        {
            // TODO unit test for the property 'ResourceName'
        }

    }

}
