/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ShipmondoApi.Dotnet.Client;
using ShipmondoApi.Dotnet.Api;
// uncomment below to import models
//using ShipmondoApi.Dotnet.Model;

namespace ShipmondoApi.Dotnet.Test.Api
{
    /// <summary>
    ///  Class for testing PickupRequestsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PickupRequestsApiTests : IDisposable
    {
        private PickupRequestsApi instance;

        public PickupRequestsApiTests()
        {
            instance = new PickupRequestsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PickupRequestsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PickupRequestsApi
            //Assert.IsType<PickupRequestsApi>(instance);
        }

        /// <summary>
        /// Test PickupRequestsGet
        /// </summary>
        [Fact]
        public void PickupRequestsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string carrierCode = null;
            //int? perPage = null;
            //int? page = null;
            //var response = instance.PickupRequestsGet(id, carrierCode, perPage, page);
            //Assert.IsType<List<PickupRequestNoShipments>>(response);
        }

        /// <summary>
        /// Test PickupRequestsPost
        /// </summary>
        [Fact]
        public void PickupRequestsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePickupRequestRequest body = null;
            //var response = instance.PickupRequestsPost(body);
            //Assert.IsType<PickupRequest>(response);
        }

        /// <summary>
        /// Test PickupRequestsShow
        /// </summary>
        [Fact]
        public void PickupRequestsShowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.PickupRequestsShow(id);
            //Assert.IsType<PickupRequest>(response);
        }
    }
}
