/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ShipmondoApi.Dotnet.Client;
using ShipmondoApi.Dotnet.Api;
// uncomment below to import models
//using ShipmondoApi.Dotnet.Model;

namespace ShipmondoApi.Dotnet.Test.Api
{
    /// <summary>
    ///  Class for testing QuotesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class QuotesApiTests : IDisposable
    {
        private QuotesApi instance;

        public QuotesApiTests()
        {
            instance = new QuotesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuotesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' QuotesApi
            //Assert.IsType<QuotesApi>(instance);
        }

        /// <summary>
        /// Test QuotesListPost
        /// </summary>
        [Fact]
        public void QuotesListPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateQuoteListRequest body = null;
            //var response = instance.QuotesListPost(body);
            //Assert.IsType<List<CreateQuoteResponse>>(response);
        }

        /// <summary>
        /// Test QuotesPost
        /// </summary>
        [Fact]
        public void QuotesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateQuoteRequest body = null;
            //var response = instance.QuotesPost(body);
            //Assert.IsType<CreateQuoteResponse>(response);
        }
    }
}
