/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ShipmondoApi.Dotnet.Client;
using ShipmondoApi.Dotnet.Api;
// uncomment below to import models
//using ShipmondoApi.Dotnet.Model;

namespace ShipmondoApi.Dotnet.Test.Api
{
    /// <summary>
    ///  Class for testing ServicePointsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ServicePointsApiTests : IDisposable
    {
        private ServicePointsApi instance;

        public ServicePointsApiTests()
        {
            instance = new ServicePointsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServicePointsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ServicePointsApi
            //Assert.IsType<ServicePointsApi>(instance);
        }

        /// <summary>
        /// Test PickupPointsGet
        /// </summary>
        [Fact]
        public void PickupPointsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string carrierCode = null;
            //string countryCode = null;
            //string zipcode = null;
            //string city = null;
            //string address = null;
            //string id = null;
            //int? quantity = null;
            //bool? collectPoints = null;
            //string productCode = null;
            //bool? inDelivery = null;
            //bool? outDelivery = null;
            //var response = instance.PickupPointsGet(carrierCode, countryCode, zipcode, city, address, id, quantity, collectPoints, productCode, inDelivery, outDelivery);
            //Assert.IsType<List<ServicePoint>>(response);
        }
    }
}
