/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ShipmondoApi.Dotnet.Client.OpenAPIDateConverter;

namespace ShipmondoApi.Dotnet.Model
{
    /// <summary>
    /// CustomsGood
    /// </summary>
    [DataContract(Name = "CustomsGood")]
    public partial class CustomsGood : IEquatable<CustomsGood>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomsGood" /> class.
        /// </summary>
        /// <param name="quantity">Quantity of the good in the shipment..</param>
        /// <param name="countryCode">Country code of origin of the good..</param>
        /// <param name="content">Description of the good..</param>
        /// <param name="commodityCode">Commodity code (tariff/HS code) of the good..</param>
        /// <param name="unitValue">Value of the good per unit..</param>
        /// <param name="unitWeight">Weight in grams of the good per unit..</param>
        public CustomsGood(int quantity = default(int), string countryCode = default(string), string content = default(string), string commodityCode = default(string), decimal unitValue = default(decimal), int unitWeight = default(int))
        {
            this.Quantity = quantity;
            this.CountryCode = countryCode;
            this.Content = content;
            this.CommodityCode = commodityCode;
            this.UnitValue = unitValue;
            this.UnitWeight = unitWeight;
        }

        /// <summary>
        /// Quantity of the good in the shipment.
        /// </summary>
        /// <value>Quantity of the good in the shipment.</value>
        /// <example>2</example>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public int Quantity { get; set; }

        /// <summary>
        /// Country code of origin of the good.
        /// </summary>
        /// <value>Country code of origin of the good.</value>
        /// <example>&quot;DK&quot;</example>
        [DataMember(Name = "country_code", EmitDefaultValue = false)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Description of the good.
        /// </summary>
        /// <value>Description of the good.</value>
        /// <example>&quot;Cotton t-shirt&quot;</example>
        [DataMember(Name = "content", EmitDefaultValue = false)]
        public string Content { get; set; }

        /// <summary>
        /// Commodity code (tariff/HS code) of the good.
        /// </summary>
        /// <value>Commodity code (tariff/HS code) of the good.</value>
        /// <example>&quot;6109100010&quot;</example>
        [DataMember(Name = "commodity_code", EmitDefaultValue = false)]
        public string CommodityCode { get; set; }

        /// <summary>
        /// Value of the good per unit.
        /// </summary>
        /// <value>Value of the good per unit.</value>
        /// <example>122.5</example>
        [DataMember(Name = "unit_value", EmitDefaultValue = false)]
        public decimal UnitValue { get; set; }

        /// <summary>
        /// Weight in grams of the good per unit.
        /// </summary>
        /// <value>Weight in grams of the good per unit.</value>
        /// <example>110</example>
        [DataMember(Name = "unit_weight", EmitDefaultValue = false)]
        public int UnitWeight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomsGood {\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  CommodityCode: ").Append(CommodityCode).Append("\n");
            sb.Append("  UnitValue: ").Append(UnitValue).Append("\n");
            sb.Append("  UnitWeight: ").Append(UnitWeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustomsGood);
        }

        /// <summary>
        /// Returns true if CustomsGood instances are equal
        /// </summary>
        /// <param name="input">Instance of CustomsGood to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustomsGood input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Quantity == input.Quantity ||
                    this.Quantity.Equals(input.Quantity)
                ) && 
                (
                    this.CountryCode == input.CountryCode ||
                    (this.CountryCode != null &&
                    this.CountryCode.Equals(input.CountryCode))
                ) && 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.CommodityCode == input.CommodityCode ||
                    (this.CommodityCode != null &&
                    this.CommodityCode.Equals(input.CommodityCode))
                ) && 
                (
                    this.UnitValue == input.UnitValue ||
                    this.UnitValue.Equals(input.UnitValue)
                ) && 
                (
                    this.UnitWeight == input.UnitWeight ||
                    this.UnitWeight.Equals(input.UnitWeight)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Quantity.GetHashCode();
                if (this.CountryCode != null)
                {
                    hashCode = (hashCode * 59) + this.CountryCode.GetHashCode();
                }
                if (this.Content != null)
                {
                    hashCode = (hashCode * 59) + this.Content.GetHashCode();
                }
                if (this.CommodityCode != null)
                {
                    hashCode = (hashCode * 59) + this.CommodityCode.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.UnitValue.GetHashCode();
                hashCode = (hashCode * 59) + this.UnitWeight.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
