/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ShipmondoApi.Dotnet.Client.OpenAPIDateConverter;

namespace ShipmondoApi.Dotnet.Model
{
    /// <summary>
    /// DraftShipment
    /// </summary>
    [DataContract(Name = "DraftShipment")]
    public partial class DraftShipment : IEquatable<DraftShipment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DraftShipment" /> class.
        /// </summary>
        /// <param name="id">Unique identifier of the object..</param>
        /// <param name="smsNotification">True if SMS notification should be used when creating shipment. (default to false).</param>
        /// <param name="emailNotification">True if email notification should be used when creating shipment. (default to false).</param>
        /// <param name="orderId">The external order ID for draft shipment. It will appear as a reference on the shipment created from the draft if no reference is set..</param>
        /// <param name="reference">The external reference for which the object has been created. It will appear as a reference on the shipment created from the draft..</param>
        /// <param name="source">The source of the draft shipment..</param>
        /// <param name="carrierCode">The code of the carrier that should be used when creating a shipment from the draft..</param>
        /// <param name="productCode">The code of the carrier product that should be used when creating a shipment from the draft..</param>
        /// <param name="serviceCodes">The codes of the carrier product services that should be used when creating a shipment from the draft..</param>
        /// <param name="archived">True if archived automatically or by the user. (default to false).</param>
        /// <param name="labelCreated">True if a shipment is created for the draft shipment. (default to false).</param>
        /// <param name="shipmentId">Unique identifier of the created shipment..</param>
        /// <param name="createdAt">ISO 8601 datetime the object was created..</param>
        /// <param name="updatedAt">Datetime when the object was updated..</param>
        /// <param name="sender">sender.</param>
        /// <param name="receiver">receiver.</param>
        /// <param name="servicePoint">servicePoint.</param>
        public DraftShipment(int id = default(int), bool smsNotification = false, bool emailNotification = false, string orderId = default(string), string reference = default(string), string source = default(string), string carrierCode = default(string), string productCode = default(string), string serviceCodes = default(string), bool archived = false, bool labelCreated = false, int shipmentId = default(int), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime), Sender sender = default(Sender), Receiver receiver = default(Receiver), ServicePointSimple servicePoint = default(ServicePointSimple))
        {
            this.Id = id;
            this.SmsNotification = smsNotification;
            this.EmailNotification = emailNotification;
            this.OrderId = orderId;
            this.Reference = reference;
            this.Source = source;
            this.CarrierCode = carrierCode;
            this.ProductCode = productCode;
            this.ServiceCodes = serviceCodes;
            this.Archived = archived;
            this.LabelCreated = labelCreated;
            this.ShipmentId = shipmentId;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Sender = sender;
            this.Receiver = receiver;
            this.ServicePoint = servicePoint;
        }

        /// <summary>
        /// Unique identifier of the object.
        /// </summary>
        /// <value>Unique identifier of the object.</value>
        /// <example>11460</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// True if SMS notification should be used when creating shipment.
        /// </summary>
        /// <value>True if SMS notification should be used when creating shipment.</value>
        [DataMember(Name = "sms_notification", EmitDefaultValue = true)]
        public bool SmsNotification { get; set; }

        /// <summary>
        /// True if email notification should be used when creating shipment.
        /// </summary>
        /// <value>True if email notification should be used when creating shipment.</value>
        [DataMember(Name = "email_notification", EmitDefaultValue = true)]
        public bool EmailNotification { get; set; }

        /// <summary>
        /// The external order ID for draft shipment. It will appear as a reference on the shipment created from the draft if no reference is set.
        /// </summary>
        /// <value>The external order ID for draft shipment. It will appear as a reference on the shipment created from the draft if no reference is set.</value>
        /// <example>&quot;1000002345&quot;</example>
        [DataMember(Name = "order_id", EmitDefaultValue = false)]
        public string OrderId { get; set; }

        /// <summary>
        /// The external reference for which the object has been created. It will appear as a reference on the shipment created from the draft.
        /// </summary>
        /// <value>The external reference for which the object has been created. It will appear as a reference on the shipment created from the draft.</value>
        /// <example>&quot;Webshop 5678&quot;</example>
        [DataMember(Name = "reference", EmitDefaultValue = false)]
        public string Reference { get; set; }

        /// <summary>
        /// The source of the draft shipment.
        /// </summary>
        /// <value>The source of the draft shipment.</value>
        /// <example>&quot;API&quot;</example>
        [DataMember(Name = "source", EmitDefaultValue = false)]
        public string Source { get; set; }

        /// <summary>
        /// The code of the carrier that should be used when creating a shipment from the draft.
        /// </summary>
        /// <value>The code of the carrier that should be used when creating a shipment from the draft.</value>
        /// <example>&quot;gls&quot;</example>
        [DataMember(Name = "carrier_code", EmitDefaultValue = false)]
        public string CarrierCode { get; set; }

        /// <summary>
        /// The code of the carrier product that should be used when creating a shipment from the draft.
        /// </summary>
        /// <value>The code of the carrier product that should be used when creating a shipment from the draft.</value>
        /// <example>&quot;GLSDK_SD&quot;</example>
        [DataMember(Name = "product_code", EmitDefaultValue = false)]
        public string ProductCode { get; set; }

        /// <summary>
        /// The codes of the carrier product services that should be used when creating a shipment from the draft.
        /// </summary>
        /// <value>The codes of the carrier product services that should be used when creating a shipment from the draft.</value>
        /// <example>&quot;EMAIL_NT,SMS_NT&quot;</example>
        [DataMember(Name = "service_codes", EmitDefaultValue = false)]
        public string ServiceCodes { get; set; }

        /// <summary>
        /// True if archived automatically or by the user.
        /// </summary>
        /// <value>True if archived automatically or by the user.</value>
        [DataMember(Name = "archived", EmitDefaultValue = true)]
        public bool Archived { get; set; }

        /// <summary>
        /// True if a shipment is created for the draft shipment.
        /// </summary>
        /// <value>True if a shipment is created for the draft shipment.</value>
        [DataMember(Name = "label_created", EmitDefaultValue = true)]
        public bool LabelCreated { get; set; }

        /// <summary>
        /// Unique identifier of the created shipment.
        /// </summary>
        /// <value>Unique identifier of the created shipment.</value>
        /// <example>123456</example>
        [DataMember(Name = "shipment_id", EmitDefaultValue = false)]
        public int ShipmentId { get; set; }

        /// <summary>
        /// ISO 8601 datetime the object was created.
        /// </summary>
        /// <value>ISO 8601 datetime the object was created.</value>
        /// <example>&quot;2017-06-16T06:25:44.557Z&quot;</example>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Datetime when the object was updated.
        /// </summary>
        /// <value>Datetime when the object was updated.</value>
        /// <example>&quot;2017-06-16T06:25:44.557Z&quot;</example>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>
        [DataMember(Name = "sender", EmitDefaultValue = false)]
        public Sender Sender { get; set; }

        /// <summary>
        /// Gets or Sets Receiver
        /// </summary>
        [DataMember(Name = "receiver", EmitDefaultValue = false)]
        public Receiver Receiver { get; set; }

        /// <summary>
        /// Gets or Sets ServicePoint
        /// </summary>
        [DataMember(Name = "service_point", EmitDefaultValue = false)]
        public ServicePointSimple ServicePoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DraftShipment {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SmsNotification: ").Append(SmsNotification).Append("\n");
            sb.Append("  EmailNotification: ").Append(EmailNotification).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  CarrierCode: ").Append(CarrierCode).Append("\n");
            sb.Append("  ProductCode: ").Append(ProductCode).Append("\n");
            sb.Append("  ServiceCodes: ").Append(ServiceCodes).Append("\n");
            sb.Append("  Archived: ").Append(Archived).Append("\n");
            sb.Append("  LabelCreated: ").Append(LabelCreated).Append("\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Receiver: ").Append(Receiver).Append("\n");
            sb.Append("  ServicePoint: ").Append(ServicePoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DraftShipment);
        }

        /// <summary>
        /// Returns true if DraftShipment instances are equal
        /// </summary>
        /// <param name="input">Instance of DraftShipment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DraftShipment input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.SmsNotification == input.SmsNotification ||
                    this.SmsNotification.Equals(input.SmsNotification)
                ) && 
                (
                    this.EmailNotification == input.EmailNotification ||
                    this.EmailNotification.Equals(input.EmailNotification)
                ) && 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                ) && 
                (
                    this.Reference == input.Reference ||
                    (this.Reference != null &&
                    this.Reference.Equals(input.Reference))
                ) && 
                (
                    this.Source == input.Source ||
                    (this.Source != null &&
                    this.Source.Equals(input.Source))
                ) && 
                (
                    this.CarrierCode == input.CarrierCode ||
                    (this.CarrierCode != null &&
                    this.CarrierCode.Equals(input.CarrierCode))
                ) && 
                (
                    this.ProductCode == input.ProductCode ||
                    (this.ProductCode != null &&
                    this.ProductCode.Equals(input.ProductCode))
                ) && 
                (
                    this.ServiceCodes == input.ServiceCodes ||
                    (this.ServiceCodes != null &&
                    this.ServiceCodes.Equals(input.ServiceCodes))
                ) && 
                (
                    this.Archived == input.Archived ||
                    this.Archived.Equals(input.Archived)
                ) && 
                (
                    this.LabelCreated == input.LabelCreated ||
                    this.LabelCreated.Equals(input.LabelCreated)
                ) && 
                (
                    this.ShipmentId == input.ShipmentId ||
                    this.ShipmentId.Equals(input.ShipmentId)
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                ) && 
                (
                    this.Sender == input.Sender ||
                    (this.Sender != null &&
                    this.Sender.Equals(input.Sender))
                ) && 
                (
                    this.Receiver == input.Receiver ||
                    (this.Receiver != null &&
                    this.Receiver.Equals(input.Receiver))
                ) && 
                (
                    this.ServicePoint == input.ServicePoint ||
                    (this.ServicePoint != null &&
                    this.ServicePoint.Equals(input.ServicePoint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                hashCode = (hashCode * 59) + this.SmsNotification.GetHashCode();
                hashCode = (hashCode * 59) + this.EmailNotification.GetHashCode();
                if (this.OrderId != null)
                {
                    hashCode = (hashCode * 59) + this.OrderId.GetHashCode();
                }
                if (this.Reference != null)
                {
                    hashCode = (hashCode * 59) + this.Reference.GetHashCode();
                }
                if (this.Source != null)
                {
                    hashCode = (hashCode * 59) + this.Source.GetHashCode();
                }
                if (this.CarrierCode != null)
                {
                    hashCode = (hashCode * 59) + this.CarrierCode.GetHashCode();
                }
                if (this.ProductCode != null)
                {
                    hashCode = (hashCode * 59) + this.ProductCode.GetHashCode();
                }
                if (this.ServiceCodes != null)
                {
                    hashCode = (hashCode * 59) + this.ServiceCodes.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Archived.GetHashCode();
                hashCode = (hashCode * 59) + this.LabelCreated.GetHashCode();
                hashCode = (hashCode * 59) + this.ShipmentId.GetHashCode();
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.UpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedAt.GetHashCode();
                }
                if (this.Sender != null)
                {
                    hashCode = (hashCode * 59) + this.Sender.GetHashCode();
                }
                if (this.Receiver != null)
                {
                    hashCode = (hashCode * 59) + this.Receiver.GetHashCode();
                }
                if (this.ServicePoint != null)
                {
                    hashCode = (hashCode * 59) + this.ServicePoint.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
