/*
 * Shipmondo API
 *
 * A unofficial thirdparty library for shipmondo api for dotnet
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ShipmondoApi.Dotnet.Client.OpenAPIDateConverter;

namespace ShipmondoApi.Dotnet.Model
{
    /// <summary>
    /// PackingSlipData
    /// </summary>
    [DataContract(Name = "PackingSlipData")]
    public partial class PackingSlipData : IEquatable<PackingSlipData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PackingSlipData" /> class.
        /// </summary>
        /// <param name="orderFulfillmentId">The ID of the order fulfillment..</param>
        /// <param name="base64">Data encoded in Base64 format..</param>
        /// <param name="fileFormat">File format for the returned PDF data..</param>
        public PackingSlipData(int orderFulfillmentId = default(int), string base64 = default(string), string fileFormat = default(string))
        {
            this.OrderFulfillmentId = orderFulfillmentId;
            this.Base64 = base64;
            this.FileFormat = fileFormat;
        }

        /// <summary>
        /// The ID of the order fulfillment.
        /// </summary>
        /// <value>The ID of the order fulfillment.</value>
        /// <example>833</example>
        [DataMember(Name = "order_fulfillment_id", EmitDefaultValue = false)]
        public int OrderFulfillmentId { get; set; }

        /// <summary>
        /// Data encoded in Base64 format.
        /// </summary>
        /// <value>Data encoded in Base64 format.</value>
        /// <example>&quot;JVBERi0xLjMKJf//////AAAAAA...&quot;</example>
        [DataMember(Name = "base64", EmitDefaultValue = false)]
        public string Base64 { get; set; }

        /// <summary>
        /// File format for the returned PDF data.
        /// </summary>
        /// <value>File format for the returned PDF data.</value>
        /// <example>&quot;pdf&quot;</example>
        [DataMember(Name = "file_format", EmitDefaultValue = false)]
        public string FileFormat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PackingSlipData {\n");
            sb.Append("  OrderFulfillmentId: ").Append(OrderFulfillmentId).Append("\n");
            sb.Append("  Base64: ").Append(Base64).Append("\n");
            sb.Append("  FileFormat: ").Append(FileFormat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PackingSlipData);
        }

        /// <summary>
        /// Returns true if PackingSlipData instances are equal
        /// </summary>
        /// <param name="input">Instance of PackingSlipData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PackingSlipData input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OrderFulfillmentId == input.OrderFulfillmentId ||
                    this.OrderFulfillmentId.Equals(input.OrderFulfillmentId)
                ) && 
                (
                    this.Base64 == input.Base64 ||
                    (this.Base64 != null &&
                    this.Base64.Equals(input.Base64))
                ) && 
                (
                    this.FileFormat == input.FileFormat ||
                    (this.FileFormat != null &&
                    this.FileFormat.Equals(input.FileFormat))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.OrderFulfillmentId.GetHashCode();
                if (this.Base64 != null)
                {
                    hashCode = (hashCode * 59) + this.Base64.GetHashCode();
                }
                if (this.FileFormat != null)
                {
                    hashCode = (hashCode * 59) + this.FileFormat.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
