name: Publish to nuget
on:
  workflow_dispatch:
  release:
    types: [released,prereleased]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.x'
      #- name: "build and test"
      #  run: dotnet build && dotnet test
      - name: "dotnet pack"
        run: dotnet pack src/ShipmondoApi.Dotnet/ShipmondoApi.Dotnet.csproj --include-symbols --include-source --output nupkgs
      - name: "dotnet nuget push"
        run: dotnet nuget push "nupkgs/*.symbols.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json